// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nhimeye.data.domain;

import com.nhimeye.data.domain.FolderIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FolderIntegrationTest_Roo_Configurable {
    
    declare @type: FolderIntegrationTest: @Configurable;
    
}
