// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nhimeye.data.domain;

import com.nhimeye.data.domain.FolderDataOnDemand;
import com.nhimeye.data.domain.FolderIntegrationTest;
import com.nhimeye.data.service.FolderService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect FolderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FolderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FolderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private FolderDataOnDemand FolderIntegrationTest.dod;
    
    @Autowired
    FolderService FolderIntegrationTest.folderService;
    
    @Test
    public void FolderIntegrationTest.testCountAllFolders() {
        Assert.assertNotNull("Data on demand for 'Folder' failed to initialize correctly", dod.getRandomFolder());
        long count = folderService.countAllFolders();
        Assert.assertTrue("Counter for 'Folder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FolderIntegrationTest.testFindFolder() {
        Folder obj = dod.getRandomFolder();
        Assert.assertNotNull("Data on demand for 'Folder' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Folder' failed to provide an identifier", id);
        obj = folderService.findFolder(id);
        Assert.assertNotNull("Find method for 'Folder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Folder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FolderIntegrationTest.testFindAllFolders() {
        Assert.assertNotNull("Data on demand for 'Folder' failed to initialize correctly", dod.getRandomFolder());
        long count = folderService.countAllFolders();
        Assert.assertTrue("Too expensive to perform a find all test for 'Folder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Folder> result = folderService.findAllFolders();
        Assert.assertNotNull("Find all method for 'Folder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Folder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FolderIntegrationTest.testFindFolderEntries() {
        Assert.assertNotNull("Data on demand for 'Folder' failed to initialize correctly", dod.getRandomFolder());
        long count = folderService.countAllFolders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Folder> result = folderService.findFolderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Folder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Folder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FolderIntegrationTest.testSaveFolder() {
        Assert.assertNotNull("Data on demand for 'Folder' failed to initialize correctly", dod.getRandomFolder());
        Folder obj = dod.getNewTransientFolder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Folder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Folder' identifier to be null", obj.getId());
        folderService.saveFolder(obj);
        Assert.assertNotNull("Expected 'Folder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FolderIntegrationTest.testDeleteFolder() {
        Folder obj = dod.getRandomFolder();
        Assert.assertNotNull("Data on demand for 'Folder' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Folder' failed to provide an identifier", id);
        obj = folderService.findFolder(id);
        folderService.deleteFolder(obj);
        Assert.assertNull("Failed to remove 'Folder' with identifier '" + id + "'", folderService.findFolder(id));
    }
    
}
