// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nhimeye.data.domain;

import com.nhimeye.data.domain.PermissionSectionIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PermissionSectionIntegrationTest_Roo_Configurable {
    
    declare @type: PermissionSectionIntegrationTest: @Configurable;
    
}
