// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nhimeye.data.domain;

import com.nhimeye.data.domain.RecordTypeDataOnDemand;
import com.nhimeye.data.domain.RecordTypeIntegrationTest;
import com.nhimeye.data.service.RecordTypeService;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect RecordTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RecordTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RecordTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private RecordTypeDataOnDemand RecordTypeIntegrationTest.dod;
    
    @Autowired
    RecordTypeService RecordTypeIntegrationTest.recordTypeService;
    
    @Test
    public void RecordTypeIntegrationTest.testCountAllRecordTypes() {
        Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", dod.getRandomRecordType());
        long count = recordTypeService.countAllRecordTypes();
        Assert.assertTrue("Counter for 'RecordType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RecordTypeIntegrationTest.testFindRecordType() {
        RecordType obj = dod.getRandomRecordType();
        Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RecordType' failed to provide an identifier", id);
        obj = recordTypeService.findRecordType(id);
        Assert.assertNotNull("Find method for 'RecordType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RecordType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RecordTypeIntegrationTest.testFindAllRecordTypes() {
        Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", dod.getRandomRecordType());
        long count = recordTypeService.countAllRecordTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'RecordType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RecordType> result = recordTypeService.findAllRecordTypes();
        Assert.assertNotNull("Find all method for 'RecordType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RecordType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RecordTypeIntegrationTest.testFindRecordTypeEntries() {
        Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", dod.getRandomRecordType());
        long count = recordTypeService.countAllRecordTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RecordType> result = recordTypeService.findRecordTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RecordType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RecordType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RecordTypeIntegrationTest.testSaveRecordType() {
        Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", dod.getRandomRecordType());
        RecordType obj = dod.getNewTransientRecordType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RecordType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RecordType' identifier to be null", obj.getId());
        recordTypeService.saveRecordType(obj);
        Assert.assertNotNull("Expected 'RecordType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RecordTypeIntegrationTest.testDeleteRecordType() {
        RecordType obj = dod.getRandomRecordType();
        Assert.assertNotNull("Data on demand for 'RecordType' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RecordType' failed to provide an identifier", id);
        obj = recordTypeService.findRecordType(id);
        recordTypeService.deleteRecordType(obj);
        Assert.assertNull("Failed to remove 'RecordType' with identifier '" + id + "'", recordTypeService.findRecordType(id));
    }
    
}
