// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nhimeye.data.domain;

import com.nhimeye.data.domain.RecordType;
import com.nhimeye.data.domain.RecordTypeDataOnDemand;
import com.nhimeye.data.reference.Type;
import com.nhimeye.data.service.RecordTypeService;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect RecordTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: RecordTypeDataOnDemand: @Component;
    
    private Random RecordTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<RecordType> RecordTypeDataOnDemand.data;
    
    @Autowired
    RecordTypeService RecordTypeDataOnDemand.recordTypeService;
    
    public RecordType RecordTypeDataOnDemand.getNewTransientRecordType(int index) {
        RecordType obj = new RecordType();
        setDescription(obj, index);
        setName(obj, index);
        setType(obj, index);
        return obj;
    }
    
    public void RecordTypeDataOnDemand.setDescription(RecordType obj, int index) {
        String description = "description_" + index;
        if (description.length() > 250) {
            description = description.substring(0, 250);
        }
        obj.setDescription(description);
    }
    
    public void RecordTypeDataOnDemand.setName(RecordType obj, int index) {
        String name = "name_" + index;
        if (name.length() > 125) {
            name = new Random().nextInt(10) + name.substring(1, 125);
        }
        obj.setName(name);
    }
    
    public void RecordTypeDataOnDemand.setType(RecordType obj, int index) {
        Type type = Type.class.getEnumConstants()[0];
        obj.setType(type);
    }
    
    public RecordType RecordTypeDataOnDemand.getSpecificRecordType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        RecordType obj = data.get(index);
        BigInteger id = obj.getId();
        return recordTypeService.findRecordType(id);
    }
    
    public RecordType RecordTypeDataOnDemand.getRandomRecordType() {
        init();
        RecordType obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return recordTypeService.findRecordType(id);
    }
    
    public boolean RecordTypeDataOnDemand.modifyRecordType(RecordType obj) {
        return false;
    }
    
    public void RecordTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = recordTypeService.findRecordTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'RecordType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<RecordType>();
        for (int i = 0; i < 10; i++) {
            RecordType obj = getNewTransientRecordType(i);
            try {
                recordTypeService.saveRecordType(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
